### ISSUE TITLE
我有意愿加入你们的团队！

### ISSUE THREAD

**Issue by iiewad** [railsgirlsjr/JoinUs#2]
我在ruby-china社区看到你的帖子，对这个项目很感兴趣。
我刚从大学毕业，写ruby有一年多时间了，现在在长沙从事后端开发。
主要想参与这种项目来提升自己。
期待你的回复：）

**Comment by usagiryu** [comment]
谢谢你对这个项目的关注，我们现在再开放招收团队。为了方便更好的安排工作，请问是否有联系的邮箱方便我们来讨论工作的细节。

**Comment by iiewad** [comment]
@tuzimoe  我的联络邮箱：lidawei.me@gmail.com

**Comment by usagiryu** [comment]
cheers
